### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by BigNatty35** [BigNatty35/Regretsy#2]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by wongshington** [comment]
- [ ] the sign in letters inside the button kinda stack when the page gets a little small. (try min-width: 45px)
- [ ] errors shouldn't persist from one form to the next
- [ ] try and cut down on some of the white space on the form. it looks pretty empty

**Comment by BigNatty35** [comment]
I fixed the sign in button and the errors on the form.

**Comment by wongshington** [comment]
- [ ] the errors should still render in the same spot for either form though
  - the original site has them off the side, which could be cool to try out also
- [ ] style up the forms themselves a bit more. they might not need to be so big if the white space is proving difficult to style up
